<?php
header('Content-Type: application/json');

// Helper to send JSON response
function jsonResponse($status, $message, $data = []) {
    echo json_encode(array_merge(['status' => $status, 'message' => $message], $data));
    exit;
}

// Get JSON input
$input = json_decode(file_get_contents('php://input'), true);
if (!$input) {
    jsonResponse('error', 'Invalid Request');
}

$action = $input['action'] ?? '';
$dbConfig = $input['db'] ?? [];
$adminConfig = $input['admin'] ?? [];

if (file_exists(__DIR__ . '/../config/installed.lock')) {
    jsonResponse('error', 'Aplikasi sudah terinstall.');
}

if ($action === 'test_connection') {
    $host = $dbConfig['host'];
    $user = $dbConfig['username'];
    $pass = $dbConfig['password'];
    $name = $dbConfig['name'];

    // Try connecting to server first (without DB name, in case it doesn't exist)
    $conn = @new mysqli($host, $user, $pass);

    if ($conn->connect_error) {
        jsonResponse('error', 'Koneksi ke server database gagal: ' . $conn->connect_error);
    }
    
    // Check if we have CREATE privileges or if DB exists
    // We just return success if we can connect to server.
    // The actual DB creation will happen in install step.
    
    jsonResponse('success', 'Koneksi berhasil!');
}

if ($action === 'install') {
    $host = $dbConfig['host'];
    $user = $dbConfig['username'];
    $pass = $dbConfig['password'];
    $name = $dbConfig['name'];

    // 1. Write Config File
    $configContent = "<?php\n\n";
    $configContent .= "// Auto-generated by Installer\n";
    $configContent .= "\$host     = '" . addslashes($host) . "';\n";
    $configContent .= "\$username = '" . addslashes($user) . "';\n";
    $configContent .= "\$password = '" . addslashes($pass) . "';\n";
    $configContent .= "\$database = '" . addslashes($name) . "';\n";
    
    $configFile = __DIR__ . '/../../config/credentials.php';
    if (!file_put_contents($configFile, $configContent)) {
        jsonResponse('error', 'Gagal menulis file konfigurasi. Cek permission folder config/');
    }

    // 2. Run Database Setup (Reusing setup_db.php logic manually to capture errors)
    // We connect and create DB
    $conn = @new mysqli($host, $user, $pass);
    if ($conn->connect_error) {
        jsonResponse('error', 'Koneksi gagal: ' . $conn->connect_error);
    }

    // Create DB
    $sql = "CREATE DATABASE IF NOT EXISTS `$name`";
    if (!$conn->query($sql)) {
        jsonResponse('error', 'Gagal membuat database: ' . $conn->error);
    }
    $conn->select_db($name);

    // Create Tables
    // Users
    $sql_users = "CREATE TABLE IF NOT EXISTS users (
        id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        role ENUM('admin', 'user') DEFAULT 'user',
        position VARCHAR(100) DEFAULT NULL,
        reset_token VARCHAR(255) DEFAULT NULL,
        reset_expires_at DATETIME DEFAULT NULL,
        signature_path VARCHAR(255) DEFAULT NULL,
        signature_prefix VARCHAR(9) DEFAULT 'DS',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )";
    if (!$conn->query($sql_users)) jsonResponse('error', 'Gagal membuat tabel users: ' . $conn->error);
    // Widen column on existing installs if necessary
    if ($colInfo = $conn->query("SHOW COLUMNS FROM users LIKE 'signature_prefix'")) {
        if ($colInfo->num_rows > 0) {
            $row = $colInfo->fetch_assoc();
            $type = $row['Type'] ?? 'varchar(3)';
            if (preg_match('/varchar\((\d+)\)/i', $type, $m)) {
                $cur = (int)$m[1];
                if ($cur < 9) {
                    @$conn->query("ALTER TABLE users MODIFY signature_prefix VARCHAR(9) DEFAULT 'DS'");
                }
            }
        }
    }

    // App Settings
    $sql_settings = "CREATE TABLE IF NOT EXISTS app_settings (
        id INT(1) PRIMARY KEY DEFAULT 1,
        app_name VARCHAR(100) DEFAULT 'DigiSign Pro',
        app_logo VARCHAR(255) DEFAULT NULL,
        maintenance_mode TINYINT(1) DEFAULT 0,
        registration_open TINYINT(1) DEFAULT 1,
        max_upload_size INT(11) DEFAULT 10485760,
        max_upload_size_bulk INT(11) DEFAULT 52428800,
        max_prefix_length INT(2) DEFAULT 3,
        timezone VARCHAR(64) DEFAULT 'Asia/Jakarta'
    )";
    if (!$conn->query($sql_settings)) jsonResponse('error', 'Gagal membuat tabel settings: ' . $conn->error);

    // Signatures
    $sql_signatures = "CREATE TABLE IF NOT EXISTS signatures (
        id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        user_id INT(11) UNSIGNED NOT NULL,
        batch_id VARCHAR(50) DEFAULT NULL,
        document_name VARCHAR(255) NULL,
        document_number VARCHAR(100) DEFAULT NULL,
        document_subject TEXT DEFAULT NULL,
        document_attachment VARCHAR(255) DEFAULT NULL,
        file_path VARCHAR(255) NULL,
        verify_code VARCHAR(100) NOT NULL UNIQUE,
        signed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        signature_type ENUM('digital', 'qr_manual') DEFAULT 'digital',
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )";
    if (!$conn->query($sql_signatures)) jsonResponse('error', 'Gagal membuat tabel signatures: ' . $conn->error);

    // Insert Default Settings
    $conn->query("INSERT IGNORE INTO app_settings (id, app_name, maintenance_mode, registration_open, max_upload_size, max_upload_size_bulk, max_prefix_length, timezone) VALUES (1, 'DigiSign Pro', 0, 1, 10485760, 52428800, 3, 'Asia/Jakarta')");

    // 3. Create Admin Account
    $adminName = $adminConfig['name'];
    $adminEmail = $adminConfig['email'];
    $adminPass = password_hash($adminConfig['password'], PASSWORD_DEFAULT);

    // Check if admin exists
    $check = $conn->query("SELECT id FROM users WHERE email = '$adminEmail'");
    if ($check->num_rows == 0) {
        $stmt = $conn->prepare("INSERT INTO users (name, email, password, role, position) VALUES (?, ?, ?, 'admin', 'Administrator')");
        $stmt->bind_param("sss", $adminName, $adminEmail, $adminPass);
        if (!$stmt->execute()) {
            jsonResponse('error', 'Gagal membuat akun admin: ' . $stmt->error);
        }
    } else {
        // Update existing admin password
        $stmt = $conn->prepare("UPDATE users SET password = ?, name = ? WHERE email = ?");
        $stmt->bind_param("sss", $adminPass, $adminName, $adminEmail);
        $stmt->execute();
    }

    // 4. Create Lock File
    $lockFile = __DIR__ . '/../../config/installed.lock';
    if (!file_put_contents($lockFile, 'INSTALLED ON ' . date('Y-m-d H:i:s'))) {
        jsonResponse('error', 'Gagal membuat lock file. Instalasi mungkin berhasil tapi tidak terkunci.');
    }

    jsonResponse('success', 'Instalasi Berhasil!');
}
?>
